---
title: "1000G_SFS"
author: "Andy Beck"
date: "2022-08-23"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction


```{r, message=FALSE, warning=FALSE}
library(tidyverse)
source("code/two_pos_new.R")
source("code/single_pos_functions.R")
```

Code for generic 2-mer generation:

```{r}
get_singleton_nmer <- function(population, subtype, n=3, data_dir = "/net/snowwhite/home/beckandy/research/1000G_LSCI/output/singletons/"){
  input_dir <- paste0(data_dir, population, "/")
  input_file <- paste0(input_dir, subtype, ".txt")
  lb <- 11 - n
  num_base <- (n*2)+1
  awk_cmd <- paste0("grep -E '^[ACGT]+$' ", input_file, "| awk '{count[substr($1, ", lb,", ", num_base,")]++}END{for(key in count)print(key\"\\t\"count[key])}'")
  df <- vroom::vroom(pipe(awk_cmd), col_names = c("motif", "singletons"), delim = "\t", show_col_types = FALSE) %>%
    separate(motif, paste0("p", 1:num_base), sep = 1:num_base)
  return(df)
}
```

```{r}
df_AFR <- get_singleton_nmer("AFR", "GC_AT", n=1) %>%
  bind_rows(get_singleton_nmer("AFR", "cpg_GC_AT", n=1) )
df_EUR <- get_singleton_nmer("EUR", "GC_AT", n=1) %>%
  bind_rows(get_singleton_nmer("EUR", "cpg_GC_AT", n=1) )

df_AFR <- df_AFR %>% 
  mutate(freq = singletons / sum(singletons))

df_EUR <- df_EUR %>% 
  mutate(freq = singletons / sum(singletons))

df <- inner_join({df_AFR %>% select(-singletons) %>% rename(AFR = freq)},
                 {df_EUR %>% select(-singletons) %>% rename(EUR = freq)},
                 by = c("p1", "p2", "p3")) %>%
  mutate(enrich = EUR / AFR)
```

```{r}
get_all_mer <- function(population, n = 3, data_dir = "/net/snowwhite/home/beckandy/research/1000G_LSCI/output/singletons/"){
  df <- get_singleton_nmer(population, "AT_CG", n, data_dir)
  df$st <- "AT_CG"
  
  for(st in c("AT_GC", "AT_TA",
              "GC_AT", "GC_TA", "GC_CG",
              "cpg_GC_AT", "cpg_GC_TA", "cpg_GC_CG")){
    df <- bind_rows(df, 
                    {get_singleton_nmer(population, st, n, data_dir) %>%
                        mutate(st = str_remove(st, "cpg_"))})
  }
  return(df)
}
```

```{r}
df_AFR <- get_all_mer("AFR", n = 1)
df_EUR <- get_all_mer("EUR", n = 1)
```

```{r}
df_AFR <- df_AFR %>%
  mutate(prop = singletons / sum(singletons))
df_EUR <- df_EUR %>%
  mutate(prop = singletons / sum(singletons))

df <- df_AFR %>%
  select(-singletons) %>%
  rename(AFR = prop) %>%
  full_join({df_EUR %>% 
      select(-singletons) %>%
      rename(EUR = prop)}, 
      by = c("p1", "p2", "p3", "st")) %>%
  mutate(enrich = EUR / AFR)

df %>%
  arrange(st, p1, p3) %>%
  ggplot(aes(p3, p1, fill = enrich)) +
  geom_tile() +
  facet_wrap(vars(st))
```

