---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# Local Sequence Context Influence on the Rate of Substitution

## Introduction

The germ line mutation rate is not uniform across the genome, and this variation is known to be associated with genomic and epigenomic features such as h3k27me3, replication timing, recombination rate, and local gc-content, among others. Here in this project we focus on evaluating the role of local sequence context on rates of substitution. In particular, we are interested in answering questions such as:

1. How far from a site of interest do nucleotides at individual positions influence the rate of substitution?
2. To what extent do pairs of flanking positions interact in determining their influence on the rate of substitution, and how does this vary as the distance between the sites and the distance from the focal site increases?
3. Are patterns of mutation-rate variation shared between global population groups?

To address these questions, we characterize the distributions of nucleotides flanking singletons observed in two data sets: the BRIDGES consortium gwas (n = ???) and the 1000G Deep Sequence data (n = 2,504). We use singletons as they are newer variants and provide a rich source of information to characterize mutation processes active in modern human populations. Our analyses are described in more detail in the documents linked to below.

## NEW: Analysis Using NYGC 1KGP
* [Single Position Models for ALL](NYGC_single_position_ALL.html)

## BRIDGES Analyses

* [Summary Statistics](BRIDGES_summary_stats.html)
* [Single Position Model Results](BRIDGES_single_position.html)
* [Two Position Model Results](BRIDGES_two_positions.html)

## 1000G Analyses

* [Summary Statistics](1000G_summary_stats.html)
* [Single Position Model Results for All Singletons](1000G_single_position_ALL.html)
* [Two Position Model Results for All Singletons](1000G_two_positions_ALL.html)
* [Cross-population Comparisons: Single Position Models](1000G_single_position_comp.html)
* [Cross-population Comparisons: Two Position Models](1000G_two_positions_comp.html)
* [2001 mer analysis](1kgp_100bp_sp.html)

## Paper Related Documents

* [Outline](outline.html)

## Miscellaneous

* [Quality Control](quality_control.html)
* [Genome-wide Counts 2-way Contingency Tables - Test of Independence](gw_chisq_ind.html)
