---
title: "NYGC_rank_re_vals"
author: "Andy Beck"
date: "2023-06-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(reactable)

## Plot options
theme_set(theme_classic())
plot_w <- 800
plot_h <- 500
plot_dpi <- 300
plot_dir <- "output/figs/"

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000")
```

## Introduction

The purpose of this document is to collect and organize the relative entropy values for the single and two position models. Primarily we are interested in noting where two-position re values are higher than single position model re values.

### Code for reading in results

```{r}
read_single_subtype_pop_res <- function(pop, subtype, 
                                        data_dir = "/net/snowwhite/home/beckandy/research/1000G_NYGC_LSCI/output/single_pos/"){
  fname <- paste0(data_dir, pop, "/", subtype, ".csv")
  df <- read_csv(fname, show_col_types = FALSE) %>%
    rowwise() %>%
    mutate(re = dev / (2 * (singletons + controls)))
  return(df)
}

read_two_subtype_pop_res <- function(pop, subtype, 
                                        data_dir = "/net/snowwhite/home/beckandy/research/1000G_NYGC_LSCI/output/two_pos/"){
  fname <- paste0(data_dir, pop, "/", subtype, ".csv")
  df <- read_csv(fname, show_col_types = FALSE) %>%
    rowwise() %>%
    mutate(re = dev / (2 * (singletons + controls)))
  return(df)
}

read_both_subtype_pop_res <- function(pop, subtype, 
                                      single_dir="/net/snowwhite/home/beckandy/research/1000G_NYGC_LSCI/output/single_pos/",
                                      two_dir = "/net/snowwhite/home/beckandy/research/1000G_NYGC_LSCI/output/two_pos/"){
  df_s <- read_single_subtype_pop_res(pop, subtype, single_dir) %>%
    select(offset, dev, re) %>%
    filter(abs(offset) < 11) %>%
    mutate(offset = as.character(offset))
  
  df_t <- read_two_subtype_pop_res(pop, subtype, two_dir) %>%
    select(rp1, rp2, dev, re) %>%
    rowwise() %>%
    mutate(offset = paste0(rp1, ", ", rp2)) %>%
    select(offset, dev, re)
  df <- bind_rows(df_s, df_t) %>%
    arrange(desc(re))
  return(df)
}
```

## Subtype Comparisons

### A to C

```{r}
df <- read_both_subtype_pop_res("ALL", "AT_CG")

df %>% reactable()
```

### A to G

```{r}
df <- read_both_subtype_pop_res("ALL", "AT_GC")

df %>% reactable()
```

### A to T

```{r}
df <- read_both_subtype_pop_res("ALL", "AT_TA")

df %>% reactable()
```

### C to A

```{r}
df <- read_both_subtype_pop_res("ALL", "GC_TA")

df %>% reactable()
```

### CpG to ApG

```{r}
df <- read_both_subtype_pop_res("ALL", "cpg_GC_TA")

df %>% reactable()
```

### C to T

```{r}
df <- read_both_subtype_pop_res("ALL", "GC_AT")

df %>% reactable()
```

### CpG to TpG

```{r}
df <- read_both_subtype_pop_res("ALL", "cpg_GC_AT")

df %>% reactable()
```

### C to G

```{r}
df <- read_both_subtype_pop_res("ALL", "GC_CG")

df %>% reactable()
```

### CpG to GpG

```{r}
df <- read_both_subtype_pop_res("ALL", "cpg_GC_CG")

df %>% reactable()
```
